{
    "name": "freezoner_custom",
    "version": "18.0.1.0.0",
    "author": "BeshoyWageh, Sabry Youssef",
    "category": "Custom",
    "summary": "Customizations for Freezoner",
    "description": "Module for Freezoner-specific customizations.",
    "depends": [
        "base",
        "mail",
        "account",
        "documents",
        "sale",
        "sale_project",
        "web",
        "client_documents",
        "hr_expense",
        "project",
        "crm",
        "cabinet_directory",
        "mass_mailing",
        # "calendar",  # COMMENTED OUT: Causes KeyError during install, calendar code disabled in models
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/res_groups.xml",
        "data/ir_sequence_data.xml",
        "data/cron.xml",
        "data/action.xml",
        "data/action_configure_email_servers.xml",
        "wizard/required_document_wizard.xml",
        "wizard/task_assignees_wizard.xml",
        "wizard/return_project_wizard.xml",
        "wizard/remarks_wizard.xml",
        "views/document_request.xml",
        "views/partner.xml",
        "views/documents.xml",
        "views/document.xml",
        "views/account_move.xml",
        "views/expense.xml",
        "views/product.xml",
        "views/project.xml",
        "views/task.xml",
        "views/crm.xml",
        "views/sale.xml",
        "views/rating.xml",
        "views/sale_portal.xml",
        "data/mails.xml",
        "data/data.xml",
        "data/survey_mail.xml",
        "data/crm_mails.xml",
        "wizard/task_wizard.xml",
        "wizard/task_next_wizard.xml",
        "wizard/sale_crm.xml",
        "wizard/update_fields.xml",
    ],
    # "assets": {
    #     "web.assets_backend": [
    #         "freezoner_custom/static/src/js/fix_documents.js",
    #     ],
    # },
    "installable": True,
    "application": False,
    "auto_install": False,
}
